<?php
include('config.php');
if(isset($_SESSION['user'])){
    if($_SESSION['user']=="SGOD"){
        header("Location:pages/SGOD/");
    }
    elseif($_SESSION['user']=="HRMO"){
        header("Location:pages/HR/");
    }
    elseif($_SESSION['user']=="SDS"){
        header("Location:pages/SDS/");
    }
	elseif($_SESSION['user']=="BUDGET"){
        header("Location:pages/BUDGET/");
    }
}
else{
    header("Location:index.php");
}